version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: python app.py
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=google_creds.json
    depends_on:
      - redis

  rq-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker.py
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=google_creds.json
    depends_on:
      - redis

  redis:
    image: redis