version: '3'
services:
  flask-app:
    image: gcr.io/apt-ai-project/flask-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: python app.py
    depends_on:
      - redis

  rq-worker:
    image: gcr.io/apt-ai-project/rq-worker
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker.py
    depends_on:
      - redis

  redis:
    image: redis