version: '3'
services:
  flask-app:
    image: gcr.io/apt-ai-project/flask-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: python app.py

  rq-worker:
    image: gcr.io/apt-ai-project/rq-worker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    command: python worker.py