version: '3'
services:
  flask-app-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    command: python app.py
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=google_creds.json
    depends_on:
      - redis-test

  rq-worker-test:
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker.py
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - GOOGLE_APPLICATION_CREDENTIALS=google_creds.json
    depends_on:
      - redis-test

  redis-test:
    image: redis