---
name: 'deploy'

on:
  push:
    branches:
      - api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 34.171.29.156 >> ~/.ssh/known_hosts

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: 'ssh://chee_heng_koh@34.171.29.156:5050:api-flask'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}